### ISSUE TITLE
dictionary changed size during iteration when calling Limb.joint_angles()

### ISSUE THREAD

**Issue by brawner** [RethinkRobotics/baxter_interface#36]
I'm calling joint_angles from a different thread than the thread in which I called rospy.init_node(), and I get about 20% of the time, the exception thrown below. Is there a way to make sure this method is thread safe?

```
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/brawner/rosjava/src/helpful_baxter/baxter_action_server/nodes/server.py", line 92, in pick_and_place
    MoveHelper.move_to_neutral("left", True)
  File "/home/brawner/workspace/src/baxter_h2r_packages/baxter_pick_and_place/src/baxter_pick_and_place/move_helper.py", line 32, in move_to_neutral
    return MoveHelper._move_to_neutral_follow_joint(limb)
  File "/home/brawner/workspace/src/baxter_h2r_packages/baxter_pick_and_place/src/baxter_pick_and_place/move_helper.py", line 58, in _move_to_neutral_follow_joint
    pick_up_shoulder = MoveHelper._create_joint_angles({"left_s1" : -0.55, "left_e1":left_e1, "left_w1": left_w1}, arm)
  File "/home/brawner/workspace/src/baxter_h2r_packages/baxter_pick_and_place/src/baxter_pick_and_place/move_helper.py", line 75, in _create_joint_angles
    base_angles = arm.joint_angles()
  File "/home/brawner/workspace/src/baxter_interface/src/baxter_interface/limb.py", line 198, in joint_angles
    return deepcopy(self._joint_angle)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 256, in _deepcopy_dict
    for key, value in x.iteritems():
RuntimeError: dictionary changed size during iteration
```

**Comment by rethink-imcmahon** [comment]
I've attempted to recreate this issue through this gist: 
https://gist.github.com/rethink-imcmahon/04e57bd556667a2fa951

I cannot seem to replicate the issue described even when I spawn 10 threads all attempting to access the same limb's joint angles. If this issue surfaces again, please post here with a distilled test setup and I will attempt to remedy it.
