### ISSUE TITLE
Navigator / Signals callback issue noted in Demo Mode

### ISSUE THREAD

**Issue by rethink-imcmahon** [RethinkRobotics/baxter_interface#63]
From the logs of a RSDK 1.1.0.55 Baxter robot as it is booting into demo mode:
```
ERROR (/rsdk_demo_ui,topics.py:691)  bad callback: <bound method Navigator._on_state of <baxter_interface.navigator.Navigator object at 0x7f9ac934ec50>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/site-packages/rospy/topics.py", line 688, in _invoke_callback
    cb(msg)
  File "/opt/hlr/rsdk_external/lib/python2.7/site-packages/baxter_interface/navigator.py", line 187, in _on_state
    self.wheel_changed(diff % (-256))
  File "/opt/hlr/rsdk_external/lib/python2.7/site-packages/baxter_dataflow/signals.py", line 47, in __call__
    for f in functions:
RuntimeError: Set changed size during iteration
```

**Comment by rethink-imcmahon** [comment]
Resolved by #64
